### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by VerumEmanio**
Hi,

This is my first time writing API documentation, so I may have made some mistakes or misinterpreted the code, but I tried to start documenting the API endpoints.

Would you please:
- [ ] Point out any errors I've made thus far.
- [ ] Send me some sample responses that I can use for the documentation.

Thanks!

### CODE REVIEW

**Comment by PhantomFury0** [comment]
When committing your code please commit and push to Release Candidate. Thank you have a great day. Please continue your sharpen your skills you've done great work.

**Comment by Gsimons2002** [comment]
Hello Mitchell, before I say anything about your code. I wanted to say thank you for taking your own time, and helping out with our class project. (es, this project is in a high school class for programming.) Our teacher has went over it and said you did a good job and is letting you do as much as you want to this project to help. But, our class has our own specific set of rules that we created to keep order in the classroom that you did not know, and that's ok. You did not have to help but you did so none of us are mad, rather we are happy that your helping us. The rule that you didn't know that was accidentally broken was when you make a pull request, you have to make one to the RC (Release-Candidate) branch. We made this rule because the Master branch is supposed to be up and running with no issues. The RC (Release-Candidate) branch is a branch that we make pull request to solve problems and do tests on. So I am gonna closed he pull request you made and ask you to make a pull request to the RC (Release-Candidate) branch. Now about the code it self, it looks good according from my teacher, but I'm still new to JavaScript so I personally don't know. So all I can say is please follow our rule, again we had no problem you didn't know. Sometimes, some of us forget to. And again, thank your for your time and effort, and please if you have more time and will, do more and learn more. Me and my entire class needs all the help we can get. 
      -Gregory Simons

P.S 
Ignore my profile pic pls :)

**Comment by VerumEmanio** [comment]
Thank you both for your kind words! @Gsimons2002 thanks for clarifying which branch I should make pull requests to. I'll make pull requests to the RC branch from now on; I should have some more changes to propose in the next hour or so. Do you use API authorization keys?

**Comment by Gsimons2002** [comment]
We do not use API authorization keys yet. This is a browser client that uses and API to the [JSFDB](https://github.com/csmith1188/JSFDB), which is a separate project. And if you need help, there is about 24 of us, and our teacher, so by all means ask.

**Comment by csmith1188** [comment]
Closing in favor of #13

**Pull request closed without merging**
